#!/bin/bash
# Script to make sure computer specs are good for a home lab

# Grab OS name
OS_Name=$(cat /etc/os-release | grep "PRETTY_NAME" | awk '{print substr($0,14,18)}')
# Grab information on HD 
Gen_HD_Info=$(lsblk | awk '/sda/ {print}')
# echo $GEN_HD_INFO
hd_size_rec=20
HD_Size=$(lsblk | awk '/sda2/ {print}' | awk '{print $4}' | awk '{print substr($0,1,2)}')
if [$hd_size_rec -gt $HD_Size]; then
	HD_Test="Your HD size needs to incease to 25GB of more"
else
	HD_Test="Your HD size is good its more than 20GB"
fi	
# CPU Count, Model Name
CPU_Count=$(lscpu | grep "CPU(s)" | awk '{print $2}' | awk 'NR==1')
Cpu_Model=$(lscpu | grep "Model name:" | awk '{print $3,$4,$5,$6}')
# Ram total on system
Ram_Total=$(free -h | awk '{print $2}' | awk 'NR==2' | awk '{print substr($0,1,3)}')
# Check system has more than 4GB of ram to run software\host clusters
Min_Ram=4
if [$Min_Ram -gt $Ram_Total]; then
	Ram_Test="You have more than 4GB of RAM"
else
	Ram_Test="You have below 4GB of RAM you will need to increase it"
fi
# Check if drive is encrypted
Check_Enc=$(blkid /dev/sda2 | awk '{print $4}' | awk '{print substr($0,7,4)}')
ext4="ext4"
if ["$Check_Enc" == "$ext4"]; then
	Enc_message="Encrpyted"
else
	Enc_message="Not Encrypted"
fi
# Grab IP address of system
IP=$(hostname -I | awk '{print substr($0,0,10)}')

echo "Checking system specs"
echo "You are running ${OS_Name}"
echo "Your HD size is ${HD_Size}GB and its ${Enc_message}"
echo ${HD_Test}
echo "Your RAM size is ${Ram_Total}GB"
echo "Your CPU model is ${Cpu_Model} with ${CPU_Count} cores"

